const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.scrollto,
		C3.Behaviors.TileMovement,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.jumpthru,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.TileMovement.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Platform.Cnds.IsDoubleJumpEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.MoveToTop
	];
};
self.C3_JsPropNameTable = [
	{Cenário: 0},
	{Sólido: 0},
	{Estrutura2: 0},
	{Plataforma2: 0},
	{Piscar: 0},
	{Moíses: 0},
	{Estrutura: 0},
	{pedra: 0},
	{Estrutura3: 0},
	{perola: 0},
	{Teclado: 0},
	{Fixar: 0},
	{Texto: 0},
	{MoverPara: 0},
	{Sangue: 0},
	{Coracao1: 0},
	{Coracao2: 0},
	{Coracao3: 0},
	{Sprite: 0},
	{Coração: 0},
	{coração2: 0},
	{Coração3: 0},
	{Projétil: 0},
	{DarAVolta: 0},
	{piolho: 0},
	{planoDeFundo: 0},
	{rã: 0},
	{CentrarEm: 0},
	{MovimentoEmGrid: 0},
	{RestritoAoLayout: 0},
	{personagem: 0},
	{Final: 0},
	{FinalFalso: 0},
	{escudo: 0},
	{escudo2: 0},
	{escudo1: 0},
	{Áudio: 0},
	{ProjetorDeSombra: 0},
	{PularAtravés: 0},
	{vaquinha: 0},
	{fase_background: 0},
	{Plataforma: 0},
	{Principal_01: 0},
	{chao: 0},
	{Texto2: 0},
	{fundinho_02: 0},
	{"8Direções": 0},
	{personaInvisivel: 0},
	{MOSCA: 0},
	{MOSCA2: 0},
	{MOSCA3: 0},
	{MOSCA4: 0},
	{MOSCA5: 0},
	{MOSCA6: 0},
	{MOSCA7: 0},
	{MOSCA8: 0},
	{MOSCA9: 0},
	{MOSCA10: 0},
	{mouse1: 0},
	{v7: 0},
	{v6: 0},
	{v5: 0},
	{v4: 0},
	{v2: 0},
	{v3: 0},
	{v1: 0},
	{capsazul3: 0},
	{capsazul1: 0},
	{capsverm4: 0},
	{capsverm2: 0},
	{apoioPrateleira: 0},
	{cenario: 0},
	{armario: 0},
	{caps1: 0},
	{caps2: 0},
	{caps3: 0},
	{caps4: 0},
	{virus: 0},
	{virus2: 0},
	{virus3: 0},
	{virus4: 0},
	{coraçao01: 0},
	{coraçao02: 0},
	{coraçao3: 0},
	{virus5: 0},
	{virus6: 0},
	{virus7: 0},
	{chao01: 0},
	{personagem04: 0},
	{Msg_vitoria: 0},
	{Campo: 0},
	{Ver: 0},
	{Fal: 0},
	{Senóide: 0},
	{Spawner: 0},
	{ColunaInvisivel: 0},
	{Cronômetro: 0},
	{Temporizador: 0},
	{comecar_fase: 0},
	{ChãoInvisivel: 0},
	{Personagem_Sensor: 0},
	{BarraDeVida: 0},
	{Física: 0},
	{PedraDeFogo: 0},
	{Frango: 0},
	{Sprite2: 0},
	{Personagem06: 0},
	{Pedra06: 0},
	{base: 0},
	{moises: 0},
	{nuvem4: 0},
	{nuvem3: 0},
	{porta1: 0},
	{nuvem1: 0},
	{nuvem2: 0},
	{porta2: 0},
	{backgroud: 0},
	{Sprite3: 0},
	{ContadorPerola: 0},
	{VIDAS: 0},
	{VIDA: 0},
	{PROTECAO: 0},
	{ESCUDO: 0},
	{MOSCAS: 0},
	{Vidas2: 0},
	{ContadorCapsula: 0},
	{tempo: 0},
	{SpawningAtivo: 0},
	{tempo_ativo: 0},
	{VidaA: 0}
];

self.InstanceType = {
	Cenário: class extends self.ISpriteInstance {},
	Estrutura2: class extends self.ISpriteInstance {},
	Moíses: class extends self.ISpriteInstance {},
	Estrutura: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	Estrutura3: class extends self.ISpriteInstance {},
	perola: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Texto: class extends self.ITextInstance {},
	Sangue: class extends self.ISpriteInstance {},
	Coracao1: class extends self.ISpriteInstance {},
	Coracao2: class extends self.ISpriteInstance {},
	Coracao3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Coração: class extends self.ISpriteInstance {},
	coração2: class extends self.ISpriteInstance {},
	Coração3: class extends self.ISpriteInstance {},
	piolho: class extends self.ISpriteInstance {},
	planoDeFundo: class extends self.ISpriteInstance {},
	rã: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	Final: class extends self.ISpriteInstance {},
	FinalFalso: class extends self.ISpriteInstance {},
	escudo: class extends self.ISpriteInstance {},
	escudo2: class extends self.ISpriteInstance {},
	escudo1: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	vaquinha: class extends self.ISpriteInstance {},
	fase_background: class extends self.ITiledBackgroundInstance {},
	Principal_01: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	fundinho_02: class extends self.ITiledBackgroundInstance {},
	personaInvisivel: class extends self.ISpriteInstance {},
	MOSCA: class extends self.ISpriteInstance {},
	MOSCA2: class extends self.ISpriteInstance {},
	MOSCA3: class extends self.ISpriteInstance {},
	MOSCA4: class extends self.ISpriteInstance {},
	MOSCA5: class extends self.ISpriteInstance {},
	MOSCA6: class extends self.ISpriteInstance {},
	MOSCA7: class extends self.ISpriteInstance {},
	MOSCA8: class extends self.ISpriteInstance {},
	MOSCA9: class extends self.ISpriteInstance {},
	MOSCA10: class extends self.ISpriteInstance {},
	mouse1: class extends self.IInstance {},
	v7: class extends self.ISpriteInstance {},
	v6: class extends self.ISpriteInstance {},
	v5: class extends self.ISpriteInstance {},
	v4: class extends self.ISpriteInstance {},
	v2: class extends self.ISpriteInstance {},
	v3: class extends self.ISpriteInstance {},
	v1: class extends self.ISpriteInstance {},
	capsazul3: class extends self.ISpriteInstance {},
	capsazul1: class extends self.ISpriteInstance {},
	capsverm4: class extends self.ISpriteInstance {},
	capsverm2: class extends self.ISpriteInstance {},
	apoioPrateleira: class extends self.ISpriteInstance {},
	cenario: class extends self.ISpriteInstance {},
	armario: class extends self.ISpriteInstance {},
	caps1: class extends self.ISpriteInstance {},
	caps2: class extends self.ISpriteInstance {},
	caps3: class extends self.ISpriteInstance {},
	caps4: class extends self.ISpriteInstance {},
	virus: class extends self.ISpriteInstance {},
	virus2: class extends self.ISpriteInstance {},
	virus3: class extends self.ISpriteInstance {},
	virus4: class extends self.ISpriteInstance {},
	coraçao01: class extends self.ISpriteInstance {},
	coraçao02: class extends self.ISpriteInstance {},
	coraçao3: class extends self.ISpriteInstance {},
	virus5: class extends self.ISpriteInstance {},
	virus6: class extends self.ISpriteInstance {},
	virus7: class extends self.ISpriteInstance {},
	chao01: class extends self.ISpriteInstance {},
	personagem04: class extends self.ISpriteInstance {},
	Msg_vitoria: class extends self.ISpriteInstance {},
	Campo: class extends self.ITiledBackgroundInstance {},
	Spawner: class extends self.ISpriteInstance {},
	ColunaInvisivel: class extends self.ISpriteInstance {},
	Temporizador: class extends self.ITextInstance {},
	comecar_fase: class extends self.ISpriteInstance {},
	ChãoInvisivel: class extends self.ISpriteInstance {},
	Personagem_Sensor: class extends self.ISpriteInstance {},
	BarraDeVida: class extends self.ISpriteInstance {},
	PedraDeFogo: class extends self.ISpriteInstance {},
	Frango: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Personagem06: class extends self.ISpriteInstance {},
	Pedra06: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	moises: class extends self.ISpriteInstance {},
	nuvem4: class extends self.ISpriteInstance {},
	nuvem3: class extends self.ISpriteInstance {},
	porta1: class extends self.ISpriteInstance {},
	nuvem1: class extends self.ISpriteInstance {},
	nuvem2: class extends self.ISpriteInstance {},
	porta2: class extends self.ISpriteInstance {},
	backgroud: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}